### PR TITLE
Use DataDir in run command

### PR DESCRIPTION
**Pull request by gbraad**

### CODE REVIEW

**Comment by gbraad** [comment]
@kbsingh DataDir wasn't used in the actual run command. Added this and reformat a little...

**Comment by kbsingh** [comment]
-v ~/.che:/data:Z is in the volumes being setup, how do you mean its not being used ?

**Comment by gbraad** [comment]
@kbsingh the variable is not used. Changing the value of DataDir is not reflected in the actual run command, as there it is hardcoded.

**Comment by kbsingh** [comment]
sounds good.

**Pull request merged**
